# Generated by Django 3.2.8 on 2021-10-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inouttime', '0003_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outtime',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='outtime',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='outtime',
            name='name',
        ),
        migrations.RemoveField(
            model_name='outtime',
            name='outtime',
        ),
        migrations.AddField(
            model_name='outtime',
            name='attender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
