# Generated by Django 3.2.8 on 2021-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inouttime', '0004_auto_20211028_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outtime',
            old_name='attender',
            new_name='outtimmer',
        ),
    ]
