# Generated by Django 3.2.8 on 2021-10-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inouttime', '0006_formlastactive_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formlastactive',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='FormLastActive',
        ),
    ]
